### ISSUE TITLE
Error: Class 'IU\PHPCap\SystemFunctions' not found

### ISSUE THREAD

**Issue by hsrc-it** [aarenson/PHPCap#12]
hi,

i tried to run tests that came with phpcap but i get the following error
`Error: Class 'IU\PHPCap\SystemFunctions' not found`

It seems the class SystemFunction can not be found 

could you please help me with this issue

**Comment by mullen2** [comment]
Hi,

I will try to help. If you don't have the latest version of PHPCap, could you please upgrade to that. For running the tests, you need to follow the steps in the Developer guide: https://aarenson.github.io/PHPCap/DeveloperGuide.html, so please also do that, if you have not already.

If you are running the latest version, and have followed the steps in the Developer Guide, could you please send me
* the command you ran that generated the error
* the output it produced (if there is more than what you already sent)
* the version of PHP you are running

Jim

**Comment by hsrc-it** [comment]
Hi jim, 
Thank for reply
i used composer to install PHPCap  and the version i have is "0.3.2"
i also used the developer guide to do test, and when i run: `$ ./vendor/bin/phpunit --testsuite unit`   get no tests executed.

but when i run a specific test i get the error where `Class 'IU\PHPCap\SystemFunctions' not found`

-  the command that generated error is ` ./vendor/bin/phpunit tests/unit/FileUtilTest.php`

- Output

` PHPUnit 7.5.1 by Sebastian Bergmann and contributors.
....EEEEE                                                           9 / 9 (100%)
Time: 199 ms, Memory: 4.00MB
There were 5 errors:`
`1) IU\PHPCap\FileUtilTest::testFileToStringWithUnreadableFile
Error: Class 'IU\PHPCap\SystemFunctions' not found
C:\xampp\htdocs\HSRC-activeDirectory\tests\Unit\FileUtilTest.php:76
2) IU\PHPCap\FileUtilTest::testFileToStringWithSystemFileError
Error: Class 'IU\PHPCap\SystemFunctions' not found
C:\xampp\htdocs\HSRC-activeDirectory\tests\Unit\FileUtilTest.php:91
3) IU\PHPCap\FileUtilTest::testFileToStringWithUnkownSystemFileError
Error: Class 'IU\PHPCap\SystemFunctions' not found
C:\xampp\htdocs\HSRC-activeDirectory\tests\Unit\FileUtilTest.php:110
4) IU\PHPCap\FileUtilTest::testWriteStringToFileWithSystemFileError
Error: Class 'IU\PHPCap\SystemFunctions' not found
C:\xampp\htdocs\HSRC-activeDirectory\tests\Unit\FileUtilTest.php:126
5) IU\PHPCap\FileUtilTest::testWriteStringToFileWithUnkownSystemFileError
Error: Class 'IU\PHPCap\SystemFunctions' not found
C:\xampp\htdocs\HSRC-activeDirectory\tests\Unit\FileUtilTest.php:144
ERRORS!
Tests: 9, Assertions: 8, Errors: 5.`

- PHP version: 7.1.3

**Comment by mullen2** [comment]
Hi,

Could you elaborate on how you installed PHPCap?

The Developer Guide indicates that Git should be used to install PHPCap, and then Composer is used to install PHPCap's dependencies. In your output, it indicates version 7.5.1 of phpunit is being used, but it should indicate version 5.7.15 (since that is the version specified in the composer.json file for PHPCap).

Jim

**Comment by mullen2** [comment]
Hi,

It looks like this issue is resolved, so I plan to close it, but if you need further assistance, please let us know. The PHPUnit tests that are provided with PHPCap are intended for developers of the PHPCap software (i.e., people actually trying to _fix or enhance_ the PHPCap code), and you need to follow the directions in the Developer Guide to be able to run the tests.

Jim
